### PR TITLE
ELEC-271: Alloc relay ids for power distribution.

### PR DESCRIPTION
**Pull request by ckitagawa**
I'm adding some relay IDs for power distribution. However, we are going to have to renumber all the IDs at some point. 

Also @karlding what's with the formating of the outfiles do I have to run clang-format on them or something? Is this expected?

### CODE REVIEW

**Comment by tituschow** [comment]
We need to update the template to be pluralized as well. Suggest adding a makefile and shebang to the scripts.

**Comment by tituschow** [comment]
So how exactly does this frame thing work? Is there a way to add field descriptors? So something like first 8 bits represents x, next bit is y, etc

**Comment by ckitagawa** [comment]
Fixed the plural and shebang stuff. I'll handle the makefile or some other build script in ticket ELEC-272.

Currently frame is
```protobuf
 // NEXT TAG = 4
message Dataframe {
  enum Type { UINT64 = 0; }

  Type type = 1;
  uint32 start = 2;
  uint32 end = 3;
}
```
Essentially `Type` will indicates what type to cast the output to start and end indicate the bits corresponding to a data field in a message. ie a 64 bit message would be `start = 0`, `end = 63` with type `int64` or `uint64` as specified. This is because it was designed with the assumption we can do custom message packing but IIRC for our CAN we have decided on  8 `uint8_t`, 4 `uint16_t`, 2 `uint32_t` or 1 `uint64_t` which means an enum would probably be sufficient to encode the possibilities and simplify the interface.

We can easily add a string field or an enum that would describe what the field represents if we wanted although IMO it is just as easy to annotate with a comment in the .asciipb file.

**Comment by tituschow** [comment]
Hmm, that's a good point. Standardizing would make things a lot simpler. I'd like to make it obvious what arguments are expected for each message. Maybe a set of macros for each message?

I was thinking field names would be useful for parsing incoming data (for example, in telemetry) or giving meaningful context to the user in our source code. If we have functions for each macro, field names could be used to populate variable names.

**Comment by ckitagawa** [comment]
I just went on a walk to think about this more here is my proposal it sounds similar to what you have suggested @tituschow 

Change Dataframes
```protobuf
 // NEXT TAG = 9
message FrameU8 {
  string field_name_1 = 1;
  string field_name_2 = 2;
  string field_name_3 = 3;
  string field_name_4 = 4;
  string field_name_5 = 5;
  string field_name_6 = 6;
  string field_name_7 = 7;
  string field_name_8 = 8;
}

 // NEXT TAG = 5
message FrameU16 {
  string field_name_1 = 1;
  string field_name_2 = 2;
  string field_name_3 = 3;
  string field_name_4 = 4;
}

 // NEXT TAG = 3
message FrameU32 {
  string field_name_1 = 1;
  string field_name_2 = 2;
}

 // NEXT TAG = 2
message FrameU64 {
  string field_name_1 = 1;
}

message CanData {
  uint64 data = 1;
  oneof frame {
   FrameU8 u8_frame = 2;
   FrameU16 u16_frame = 3;
   FrameU32 u32_frame = 4;
   FrameU64 u64_frame = 5;
  }
}
```

Standardize on the following message data formats
*  8 `uint8_t`
*  4 `uint16_t`
*  2 `uint32_t`
*  1 `uint64_t`

For each type we can define an unpacking/packing function and then define a macro to pack it using verbose field names for the arguments.

```c
void can_pack_uint8(CANMessage *msg, uint16_t source_id, CANMessageID id, CANMsgType type, uint8_t f1, uint8_t f2, uint8_t f3, uint8_t f4, uint8_t f5, uint8_t f6, uint8_t f7, uint8_t f8); 

// I've omitted the id, source_id, and type but it is easy enough to populate pointer to those as well?
void can_unpack_uint8(const CANMessage *msg, uint8_t *f1, uint8_t *f2, uint8_t *f3, uint8_t *f4, uint8_t *f5, uint8_t *f6, uint8_t *f7, uint8_t *f8); 

// As an example consider an array master with only 2 MPPTs which uses a 8 uint8 for some reason.
// The argument names would come from the frame field (oneof).
// SOURCE_ID, ID, TYPE can all come from the .asciipb file.
#define CAN_PACK_ARRAY_DATA(msg_ptr, voltage_1, current_1, voltage_2, current_2) \
  can_pack_uint8(msg_ptr, SOURCE_ID, ID, TYPE, voltage_1, current_1, voltage_2, current_2, 0, 0, 0, 0)

#define CAN_UNPACK_ARRAY_DATA(msg_ptr, voltage_1_ptr, current_1_ptr, voltage_2_ptr, current_2_ptr) \
  can_unpack_uint8(msg_ptr, voltage_1_ptr, current_1_ptr, voltage_2_ptr, current_2_ptr, NULL, NULL, NULL, NULL)
```

@tituschow your thoughts on this plan? It is basically a way of producing/unloading the already existing `CANMessage` struct with automatic and clean boilerplate specific for each message.

**Comment by tituschow** [comment]
Yeah, I think that's about what I had in mind. We should also add a bool to address ELEC-202 (critical messages). Maybe even integrate the can_transmit and pending ACK request data?

**Comment by ckitagawa** [comment]
I think integrating a critical bit into transmit/ack makes the most sense? We can also have it here but I was under the impression this was just to build messages not necessarily send them? Although I suppose it could do that too. I'll merge this now since the discussion is largely unrelated to the PR.

**Pull request merged**
